/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg195_0alumnidatabase_idenney;

/**
 *
 * @author IsaacCD
 */
public class AlumniDatabaseWindow extends javax.swing.JFrame {

    /**
     * Creates new form AlumniDatabaseWindow
     */
    public AlumniDatabaseWindow() {
        initComponents();
    }

    private void createTables() {
        pkg195_1createtables_idenney.Main.main(null);
    }
    private void populateTables() {
        pkg195_2populatetables_idenney.Main.runMain(this);
    }
    private void populatePrivate() {
        pkg195_3populateprivate_idenney.Main.runMain(this);
    }
    private void deleteFromTables() {
        pkg195_4deletefromtables_idenney.Main.runMain(this);
    }
    private void alumniQueries() {
        pkg195_5alumniqueries_idenney.Main.runMain(this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonCreateTables = new javax.swing.JButton();
        buttonPopulateTables = new javax.swing.JButton();
        buttonPopulatePrivate = new javax.swing.JButton();
        buttonDeleteFromTables = new javax.swing.JButton();
        buttonAlumniQueries = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alumni Database Application");

        buttonCreateTables.setText("Go");
        buttonCreateTables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCreateTablesMouseClicked(evt);
            }
        });

        buttonPopulateTables.setText("Go");
        buttonPopulateTables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPopulateTablesMouseClicked(evt);
            }
        });

        buttonPopulatePrivate.setText("Go");
        buttonPopulatePrivate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPopulatePrivateMouseClicked(evt);
            }
        });

        buttonDeleteFromTables.setText("Go");
        buttonDeleteFromTables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDeleteFromTablesMouseClicked(evt);
            }
        });

        buttonAlumniQueries.setText("Go");
        buttonAlumniQueries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAlumniQueriesMouseClicked(evt);
            }
        });

        jLabel1.setText("195_CreateTables");

        jLabel2.setText("195_PopulateTables");

        jLabel3.setText("195_PopulatePrivate");

        jLabel4.setText("195_DeleteFromTables");

        jLabel5.setText("195_AlumniQueries");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonCreateTables)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonPopulateTables)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonPopulatePrivate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonDeleteFromTables)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonAlumniQueries)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCreateTables)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPopulateTables)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPopulatePrivate)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDeleteFromTables)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAlumniQueries)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCreateTablesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCreateTablesMouseClicked
        createTables();
    }//GEN-LAST:event_buttonCreateTablesMouseClicked

    private void buttonPopulateTablesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPopulateTablesMouseClicked
        populateTables();
    }//GEN-LAST:event_buttonPopulateTablesMouseClicked

    private void buttonPopulatePrivateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPopulatePrivateMouseClicked
        populatePrivate();
    }//GEN-LAST:event_buttonPopulatePrivateMouseClicked

    private void buttonDeleteFromTablesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDeleteFromTablesMouseClicked
        deleteFromTables();
    }//GEN-LAST:event_buttonDeleteFromTablesMouseClicked

    private void buttonAlumniQueriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAlumniQueriesMouseClicked
        alumniQueries();
    }//GEN-LAST:event_buttonAlumniQueriesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlumniDatabaseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlumniDatabaseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlumniDatabaseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlumniDatabaseWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlumniDatabaseWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAlumniQueries;
    private javax.swing.JButton buttonCreateTables;
    private javax.swing.JButton buttonDeleteFromTables;
    private javax.swing.JButton buttonPopulatePrivate;
    private javax.swing.JButton buttonPopulateTables;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
