DROP TABLE IF EXISTS majors;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS private;
DROP TABLE IF EXISTS emails;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS majorsinfo;

CREATE TABLE students ( id INT AUTO_INCREMENT PRIMARY KEY, firstName VARCHAR(40), middleName VARCHAR(40), lastName VARCHAR(40) NOT NULL );

CREATE TABLE private ( studentId INT UNIQUE PRIMARY KEY, ssn VARCHAR(11) NULL UNIQUE, noContact BOOLEAN DEFAULT FALSE, canDonate BOOLEAN DEFAULT FALSE, trackPHD BOOLEAN DEFAULT FALSE, CONSTRAINT private_id_fk_students FOREIGN KEY (studentId) REFERENCES students (id) ON DELETE CASCADE );

CREATE TABLE comments ( id INT AUTO_INCREMENT PRIMARY KEY, studentId INT, entryDate DATETIME, comments VARCHAR(255),CONSTRAINT comments_id_fk_private FOREIGN KEY (studentId) REFERENCES private (studentId) ON DELETE CASCADE );

CREATE TABLE emails ( id INT AUTO_INCREMENT PRIMARY KEY, studentId INT NOT NULL, emailAddress VARCHAR(255) NOT NULL, CONSTRAINT emails_id_fk_students FOREIGN KEY (studentId) REFERENCES students (id) ON DELETE CASCADE );

CREATE TABLE majorsinfo ( id INT AUTO_INCREMENT PRIMARY KEY, majorAbbr VARCHAR(10) UNIQUE NOT NULL, majorName VARCHAR(40) UNIQUE NOT NULL );

CREATE TABLE majors ( id INT AUTO_INCREMENT PRIMARY KEY, studentId INT NOT NULL,majorId INT NOT NULL, FOREIGN KEY (studentId) REFERENCES students (id) ON DELETE CASCADE , FOREIGN KEY (majorId) REFERENCES majorsinfo (id) ON DELETE CASCADE );
